.pragma library
.import "../../engine/Rng.js" as Rng

// Helicopter-style cave: hold to climb, let go to sink. The cave is a list
// of columns (ceiling/floor heights, 0 = top, 1 = bottom) generated by a
// smooth random walk that narrows with distance, plus the odd free-standing
// pillar to weave around. The ship sits at a fixed x and the cave scrolls.

var SHIP_X = 0.22
var SHIP_R = 0.018
var COL_W = 0.02
var VIEW_W = 1.5
var LIFT = 2.4
var GRAVITY = 1.9
var MAX_V = 0.95
var BASE_SPEED = 0.38

function gapFor(distance) { return Math.max(0.3, 0.62 - distance * 0.0009) }

function makeColumn(prev, distance) {
  var gap = gapFor(distance)
  var drift = (prev.drift || 0) * 0.85 + (Rng.random() - 0.5) * 0.03
  var centre = Math.max(gap / 2 + 0.04, Math.min(1 - gap / 2 - 0.04, prev.centre + drift))
  if (centre === prev.centre) drift = -drift
  return { top: centre - gap / 2, bottom: centre + gap / 2, centre: centre, drift: drift, pillar: null }
}

function makeState() {
  var cols = []
  var prev = { centre: 0.5, drift: 0 }
  var n = Math.ceil(VIEW_W / COL_W) + 2
  for (var i = 0; i < n; ++i) { prev = makeColumn(prev, 0); cols.push(prev) }
  return { y: 0.5, vy: 0, cols: cols, offset: 0, distance: 0, alive: true, sincePillar: 0, trail: [] }
}

function copy(s) {
  return { y: s.y, vy: s.vy, cols: s.cols, offset: s.offset, distance: s.distance, alive: s.alive,
    sincePillar: s.sincePillar, trail: s.trail }
}

function speedFor(distance) { return Math.min(0.8, BASE_SPEED + distance * 0.0012) }

// input: { up: bool }
function step(state, input, dt) {
  if (!state.alive) return state
  var s = copy(state)
  var vy = state.vy + (input.up ? -LIFT : GRAVITY) * dt
  vy = Math.max(-MAX_V, Math.min(MAX_V, vy))
  s.vy = vy
  s.y = state.y + vy * dt

  var speed = speedFor(state.distance)
  s.distance = state.distance + speed * dt * 20
  var offset = state.offset + speed * dt
  var cols = state.cols
  var since = state.sincePillar
  while (offset >= COL_W) {
    offset -= COL_W
    cols = cols.slice(1)
    var col = makeColumn(cols[cols.length - 1], s.distance)
    since++
    if (s.distance > 40 && since > 28 && Rng.random() < 0.08) {
      var span = col.bottom - col.top
      var h = span * 0.28
      var py = col.top + h * 0.3 + Rng.random() * (span - h * 1.6)
      col.pillar = { top: py, bottom: py + h }
      since = 0
    }
    cols.push(col)
  }
  s.cols = cols
  s.offset = offset
  s.sincePillar = since

  var trail = state.trail.concat([s.y])
  s.trail = trail.length > 24 ? trail.slice(trail.length - 24) : trail

  // Collide against the columns under the ship.
  for (var i = 0; i < cols.length; ++i) {
    var x0 = i * COL_W - offset
    if (x0 + COL_W < SHIP_X - SHIP_R || x0 > SHIP_X + SHIP_R) continue
    var c = cols[i]
    if (s.y - SHIP_R < c.top || s.y + SHIP_R > c.bottom) { s.alive = false; break }
    if (c.pillar && s.y + SHIP_R > c.pillar.top && s.y - SHIP_R < c.pillar.bottom) { s.alive = false; break }
  }
  return s
}

function score(state) { return Math.floor(state.distance) }
