.pragma library
.import "../../engine/Rng.js" as Rng

// Pure board logic. Puzzles are generated by solving a full grid via
// randomized backtracking, then digging holes one at a time in random
// order, keeping each hole only if a solver limited to the techniques a
// person uses (singles, locked candidates, pairs) can still finish it —
// so every puzzle can be solved by deduction, never by a forced guess.
// A unique answer alone isn't enough: some unique puzzles need trial and
// error or rare chain techniques.

function emptyGrid() {
  var g = []
  for (var r = 0; r < 9; ++r) g.push(new Array(9).fill(0))
  return g
}

function shuffled(arr) {
  var a = arr.slice()
  for (var i = a.length - 1; i > 0; --i) {
    var j = Math.floor(Rng.random() * (i + 1))
    var t = a[i]; a[i] = a[j]; a[j] = t
  }
  return a
}

function validAt(g, r, c, v) {
  for (var i = 0; i < 9; ++i) {
    if (g[r][i] === v) return false
    if (g[i][c] === v) return false
  }
  var br = Math.floor(r / 3) * 3, bc = Math.floor(c / 3) * 3
  for (var y = br; y < br + 3; ++y)
    for (var x = bc; x < bc + 3; ++x)
      if (g[y][x] === v) return false
  return true
}

function fill(g, pos) {
  if (pos === 81) return true
  var r = Math.floor(pos / 9), c = pos % 9
  var candidates = shuffled([1, 2, 3, 4, 5, 6, 7, 8, 9])
  for (var i = 0; i < candidates.length; ++i) {
    var v = candidates[i]
    if (validAt(g, r, c, v)) {
      g[r][c] = v
      if (fill(g, pos + 1)) return true
      g[r][c] = 0
    }
  }
  return false
}

function generateSolved() {
  var g = emptyGrid()
  fill(g, 0)
  return g
}

function cloneGrid(grid) {
  return grid.map(function(row) { return row.map(function(cell) { return { value: cell.value, given: cell.given } }) })
}

function withGrid(state, grid, patch) {
  var next = { grid: grid, cursor: state.cursor }
  for (var k in patch) next[k] = patch[k]
  return next
}

// Every row, column and box as a list of cell indices 0..80.
var UNITS = (function() {
  var units = []
  for (var i = 0; i < 9; ++i) {
    var row = [], col = [], box = []
    for (var k = 0; k < 9; ++k) {
      row.push(i * 9 + k)
      col.push(k * 9 + i)
      box.push((Math.floor(i / 3) * 3 + Math.floor(k / 3)) * 9 + (i % 3) * 3 + k % 3)
    }
    units.push(row, col, box)
  }
  return units
})()

function bitCount(m) { var n = 0; while (m) { m &= m - 1; n++ } return n }
function onlyDigit(m) { for (var v = 1; v <= 9; ++v) if (m === 1 << v) return v; return 0 }

// Solves like a person with pencil marks: naked and hidden singles, locked
// candidates (pointing / claiming), naked and hidden pairs. No guessing.
// `g` is a 9x9 array of digits (0 empty); true if it gets to the end.
function humanSolvable(g) {
  var val = [], cand = [], i, u, v, k
  for (i = 0; i < 81; ++i) { val.push(g[Math.floor(i / 9)][i % 9]); cand.push(0) }
  var peers = []
  for (i = 0; i < 81; ++i) peers.push([])
  for (u = 0; u < UNITS.length; ++u)
    for (k = 0; k < 9; ++k) for (var j = 0; j < 9; ++j) if (j !== k) peers[UNITS[u][k]].push(UNITS[u][j])
  for (i = 0; i < 81; ++i) {
    if (val[i]) continue
    var m = 1022
    for (k = 0; k < peers[i].length; ++k) m &= ~(1 << val[peers[i][k]])
    cand[i] = m
  }
  function set(i, v) {
    val[i] = v; cand[i] = 0
    for (var k = 0; k < peers[i].length; ++k) cand[peers[i][k]] &= ~(1 << v)
  }
  function strip(cells, keep, mask) {
    var hit = false
    for (var k = 0; k < cells.length; ++k) {
      var c = cells[k]
      if (keep.indexOf(c) >= 0 || !(cand[c] & mask)) continue
      cand[c] &= ~mask; hit = true
    }
    return hit
  }
  for (;;) {
    var progress = false, left = 0
    for (i = 0; i < 81; ++i) {
      if (val[i]) continue
      left++
      if (!cand[i]) return false
      var d = onlyDigit(cand[i])
      if (d) { set(i, d); progress = true }
    }
    if (!left) return true
    if (progress) continue
    // Hidden singles.
    for (u = 0; u < UNITS.length && !progress; ++u) for (v = 1; v <= 9 && !progress; ++v) {
      var spots = UNITS[u].filter(function(c) { return cand[c] & (1 << v) })
      if (spots.length === 1) { set(spots[0], v); progress = true }
    }
    if (progress) continue
    // Locked candidates: a digit confined to one box-line overlap within
    // either unit can go from the rest of the other.
    for (u = 0; u < UNITS.length && !progress; ++u) for (v = 1; v <= 9 && !progress; ++v) {
      var where = UNITS[u].filter(function(c) { return cand[c] & (1 << v) })
      if (where.length < 2) continue
      for (var w = 0; w < UNITS.length && !progress; ++w) {
        if (w === u) continue
        var inW = where.every(function(c) { return UNITS[w].indexOf(c) >= 0 })
        if (inW && strip(UNITS[w], where, 1 << v)) progress = true
      }
    }
    if (progress) continue
    // Naked pairs, then hidden pairs.
    for (u = 0; u < UNITS.length && !progress; ++u) {
      var cells = UNITS[u].filter(function(c) { return !val[c] })
      for (var a = 0; a < cells.length && !progress; ++a) {
        if (bitCount(cand[cells[a]]) !== 2) continue
        for (var b = a + 1; b < cells.length && !progress; ++b)
          if (cand[cells[b]] === cand[cells[a]] && strip(cells, [cells[a], cells[b]], cand[cells[a]])) progress = true
      }
      for (var v1 = 1; v1 <= 9 && !progress; ++v1) for (var v2 = v1 + 1; v2 <= 9 && !progress; ++v2) {
        var s1 = cells.filter(function(c) { return cand[c] & (1 << v1) })
        var s2 = cells.filter(function(c) { return cand[c] & (1 << v2) })
        if (s1.length !== 2 || s2.length !== 2 || s1[0] !== s2[0] || s1[1] !== s2[1]) continue
        var pair = (1 << v1) | (1 << v2)
        for (k = 0; k < 2; ++k) if (cand[s1[k]] !== pair) { cand[s1[k]] = pair; progress = true }
      }
    }
    if (!progress) return false
  }
}

function makeState(removeCount) {
  removeCount = removeCount === undefined ? 50 : removeCount
  var solved = generateSolved()
  var puzzle = solved.map(function(row) { return row.slice() })
  var order = []
  for (var p = 0; p < 81; ++p) order.push(p)
  order = shuffled(order)
  var removed = 0
  for (var o = 0; o < order.length && removed < removeCount; ++o) {
    var pr = Math.floor(order[o] / 9), pc = order[o] % 9
    var keep = puzzle[pr][pc]
    puzzle[pr][pc] = 0
    if (humanSolvable(puzzle)) removed++
    else puzzle[pr][pc] = keep
  }
  var grid = []
  for (var r = 0; r < 9; ++r) {
    var row = []
    for (var c = 0; c < 9; ++c) row.push(puzzle[r][c] ? { value: puzzle[r][c], given: true } : { value: 0, given: false })
    grid.push(row)
  }
  return { grid: grid, cursor: { x: 4, y: 4 } }
}

function moveCursor(state, dx, dy) {
  var x = Math.max(0, Math.min(8, state.cursor.x + dx))
  var y = Math.max(0, Math.min(8, state.cursor.y + dy))
  return withGrid(state, state.grid, { cursor: { x: x, y: y } })
}

// Digit entry rides the spare keys: SPACE/ENTER dials the selected cell up,
// U dials it down, both wrapping through blank (0) — the same "extra key
// rides an established idiom" pattern as Minesweeper's flag-on-undo.
function incrementCursor(state) {
  var c = state.cursor
  var cell = state.grid[c.y][c.x]
  if (cell.given) return state
  var grid = cloneGrid(state.grid)
  grid[c.y][c.x].value = (cell.value + 1) % 10
  return withGrid(state, grid, {})
}

function setCursor(state, value) {
  var c = state.cursor
  var cell = state.grid[c.y][c.x]
  if (cell.given || cell.value === value) return state
  var grid = cloneGrid(state.grid)
  grid[c.y][c.x].value = value
  return withGrid(state, grid, {})
}

function decrementCursor(state) {
  var c = state.cursor
  var cell = state.grid[c.y][c.x]
  if (cell.given) return state
  var grid = cloneGrid(state.grid)
  grid[c.y][c.x].value = (cell.value + 9) % 10
  return withGrid(state, grid, {})
}

function hasConflict(grid, x, y) {
  var v = grid[y][x].value
  if (v === 0) return false
  for (var i = 0; i < 9; ++i) {
    if (i !== x && grid[y][i].value === v) return true
    if (i !== y && grid[i][x].value === v) return true
  }
  var br = Math.floor(y / 3) * 3, bc = Math.floor(x / 3) * 3
  for (var yy = br; yy < br + 3; ++yy)
    for (var xx = bc; xx < bc + 3; ++xx)
      if ((xx !== x || yy !== y) && grid[yy][xx].value === v) return true
  return false
}

function isSolved(grid) {
  for (var y = 0; y < 9; ++y)
    for (var x = 0; x < 9; ++x) {
      if (grid[y][x].value === 0) return false
      if (hasConflict(grid, x, y)) return false
    }
  return true
}

// Live progress: how many of the editable cells are filled, and of those,
// how many aren't currently clashing with a peer (used for score).
function stats(grid) {
  var totalBlank = 0, filled = 0, correct = 0
  for (var y = 0; y < 9; ++y)
    for (var x = 0; x < 9; ++x) {
      var cell = grid[y][x]
      if (!cell.given) {
        totalBlank++
        if (cell.value !== 0) {
          filled++
          if (!hasConflict(grid, x, y)) correct++
        }
      }
    }
  return { totalBlank: totalBlank, filled: filled, correct: correct }
}

function serialize(state) {
  return { grid: state.grid, cursor: state.cursor }
}

function deserialize(obj) {
  if (!obj || !obj.grid || obj.grid.length !== 9) return null
  var grid = []
  for (var y = 0; y < 9; ++y) {
    if (!obj.grid[y] || obj.grid[y].length !== 9) return null
    var row = []
    for (var x = 0; x < 9; ++x) {
      var c = obj.grid[y][x] || {}
      row.push({ value: c.value | 0, given: !!c.given })
    }
    grid.push(row)
  }
  var cursor = obj.cursor || { x: 0, y: 0 }
  return { grid: grid, cursor: { x: cursor.x | 0, y: cursor.y | 0 } }
}
